@uri= http://localhost:5000
//
GET {{uri}}/
###
GET {{uri}}/api/todos
###
POST {{uri}}/api/todos
Content-Type: application/json

{
    "body":"Sample Todo"
}
###
PUT {{uri}}/api/todos/66dfba621bf5083b921130e7
Content-Type: application/json
###
DELETE {{uri}}/api/todos/66dfa9c58fcef4cf4d8207a6