version: '3.9'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo-todo-server
    ports:
      - 9879:27017
    volumes:
      - mongodb:/data/mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
volumes:
  mongodb:
    driver: local